name: docker-build-and-push

inputs:
  bake-target:
    description: ""
    required: true
  tag-suffix:
    description: ""
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: avyana/${{ inputs.bake-target }}
        tags: ${{ steps.meta.outputs.tags }}
        bake-target: docker-metadata-action-devel
        flavor: |
          latest=false
          suffix=${{ inputs.tag-suffix }}

    - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/bake-action@v2
      with:
        # Checking event_name for https://github.com/autowarefoundation/autoware/issues/2796
        push: ${{ github.event_name == 'schedule' || github.ref_name == github.event.repository.default_branch }}
        files: |
          docker/${{ inputs.bake-target }}/docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        set: |
          ${{ inputs.build-args }}
